### ISSUE TITLE
Updated membership "fails" for users with membership > 1 year old

### ISSUE THREAD

**Issue by melwil** [dotkom/onlineweb4#1399]
Currrently the new expiration date for memberships is determined like this:

``` python
new_expiration_date = datetime.date(membership.expiration_date.year + 1, 9, 16)
```

Source: https://github.com/dotKom/onlineweb4/blob/develop/apps/approval/views.py#L86

If a user has membership that expired in 2014, they will get 2015 as the new date, which is still an expired date.

**Comment by OptimusCrime** [comment]
Could the new date simply be the current year, or would that fuck something up?

**Comment by sklirg** [comment]
Me updating my thingy August 2016:
New date:
Septembre 2016.
So yes, it would.

**Comment by sklirg** [comment]
Fixed in #1513

**Comment by OptimusCrime** [comment]
Still happens. User had bachelor degree 2012 - 2015, and extended their membership. Membership date was sat to september 2016. Had to send a new request to set the date to 2017.

**Comment by plusk** [comment]
Me and @oleast took a quick gander at this one, and we think it should just be changing [this](onehttps://github.com/dotkom/onlineweb4/blob/972069a2ec64b6050d721ca619c66904be54eb86/apps/approval/views.py#L89) check to instead go based on 1st of July.
