### ISSUE TITLE
More informative set_password error messages and some authentication fixes

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1436]
In [`apps.authentication.views.set_password`](https://github.com/dotKom/onlineweb4/blob/v4.17.8/apps/authentication/views.py#L216) there are some edge cases not being handled gracefully, resulting in a HTTP 500 INTERNAL SERVER ERROR if triggered. 
- [x] `if rt.is_valid:` does not have an else, and there's no return statement - which means if the token is invalid for whatever reason (expired or a "fake"), an exception is thrown due to a view not returning a `HttpResponse` object. Fix by returning something, e.g. a `request.message` and a redirect to root (`/`).
- [x] Make sure any other cases returns to root with a message, simply remove L 250 `else` and unindent, adding relevant `request.messages` where appropriate.
- [x] Add minimum length password validators according to [Django 1.9 password validators](https://docs.djangoproject.com/en/1.9/topics/auth/passwords/#enabling-password-validation).
- [ ] _up for discussion_ Update RegisterToken model to have `RegisterToken.token` field as unique. If that's implemented, we can remove `if token.count() == 1` and replace it with a `get_object_or_404`, reducing code complexity, branching and readability.

**Comment by melwil** [comment]
Adding minimum length for passwords is a good idea, but please no complicated rules. Be sure to check how validation of these rules fit into form validation. Does it trigger on "user.set_password()"? Do we need to specifically validate this?

I think one of the points with not having a unique token field is that you could possibly have two tokens that had the same uuid generated for it. Another one is that it makes no sense to return 404 in my eyes. The count is a way around having to either get an object or fail with 404, allowing you to insert another error, like "Lenken er ikke gyldig, hent en ny."

**Comment by sklirg** [comment]
> Does it trigger on "user.set_password()"? Do we need to specifically validate this?
It triggers just as any other model field with a validator. https://docs.djangoproject.com/en/1.9/ref/forms/validation/

https://docs.djangoproject.com/en/1.9/topics/auth/passwords/#integrating-validation
> If one or more validators reject the password, raises a ValidationError with all the error messages from the validators.

---

Well, password reset doesn't work if there are two identical tokens. Therefore, it shouldn't be possible to have two identical tokens (rather than telling the user to try again - because we didn't verify that there is no token with the same uuid).

Regarding 404 I agree. A better approach would be to try to get it, and if it fails, return to either root or reset password view.

**Comment by sklirg** [comment]
Was not actually fixed.

**Comment by nornes** [comment]
What did we end up with on the last point? Do or don't?

**Comment by nornes** [comment]
bump 👆🏼

**Comment by sklirg** [comment]
This point
> Update RegisterToken model to have RegisterToken.token field as unique. If that's implemented, we can remove if token.count() == 1 and replace it with a get_object_or_404, reducing code complexity, branching and readability.
?

I say go.

**Comment by nornes** [comment]
I think this was fixed by #1505.

**Comment by sklirg** [comment]
The `RegisterToken.token` field is not unique, so the issue is not fixed. That targeted another issue with regards to some other use of the token.

**Comment by oleast** [comment]
I don't get this, the `RegisterToken.token` field has been `unique` since March of 2016?
There is no `if token.count() == 1` either.

I see no reason for this issue to still be open. But I may be wrong.

**Comment by sklirg** [comment]
I think the problem I was pointing out was that there was never created a migration for the field to actually be marked as unique, even though the model states it should be. Seems like that got added in 806c65f05e6f2170440a8039ebc67b560b89ed33, though.

I can't recall what else it could've been, so I agree with closing this issue :)
